# Generated by ‘nixos-generate-config’, then extended with storage mounts
# and boot modules. User data mounts (/home/stoleyy/games, /data) live in
# hosts/predator/default.nix — they need nofail + device-timeout options
# that hardware-configuration.nix doesn’t provide.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "ahci"
        "xhci_pci"
        "nvme"
        "usbhid"
      ];
      # LOAD-BEARING — do NOT remove or move to availableKernelModules. VMD is
      # disabled in BIOS but the controller persists; the kernel still needs vmd
      # to find the root NVMe by-UUID, force-loaded here so it inits before
      # Stage-1 root discovery (6.12+). Removing it = unbootable "cannot find
      # root" (PR #8 tried -> #13 bricked -> #14 this fix). Regen clobbers it.
      kernelModules = [ "vmd" ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/af8035c3-bfc3-4674-b66d-1a5f0c1e8cce";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BA72-1B01";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
