# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "nvme"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ "vmd" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/af8035c3-bfc3-4674-b66d-1a5f0c1e8cce";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BA72-1B01";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # Former NTFS games partition on nvme0n1p2 — reformatted as ext4.
  # After running: sudo mkfs.ext4 -L games /dev/nvme0n1p2
  # replace the UUID with: sudo blkid /dev/nvme0n1p2
  fileSystems."/home/stoleyy/games" = {
    device = "/dev/disk/by-uuid/efd6d32e-54f9-4e6d-965f-67279a31da47";
    fsType = "ext4";
    options = [
      "nofail"
      "defaults"
    ];
  };

  # Former Windows NVMe (nvme1n1) — wiped and repartitioned as a single ext4.
  # After running: sudo mkfs.ext4 -L data /dev/nvme1n1p1
  # replace the UUID with: sudo blkid /dev/nvme1n1p1
  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/88c50d98-1905-405d-a9c2-5ce522c9ad77";
    fsType = "ext4";
    options = [
      "nofail"
      "defaults"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
